import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-functions.js';
import { firebaseConfig } from './firebase-config.js';
const app = initializeApp(firebaseConfig), auth = getAuth(app), functions = getFunctions(app, 'asia-southeast1'), provider = new GoogleAuthProvider(); const signIn = document.querySelector('#creator-admin-sign-in'), list = document.querySelector('#creator-admin-list'), message = document.querySelector('#creator-admin-message');
function text(tag, value, className) { const node = document.createElement(tag); node.textContent = value; if (className) node.className = className; return node; }
function card(item, kind) { const card = document.createElement('article'); card.className = 'admin-card'; const details = document.createElement('div'); const title = kind === 'profile' ? item.displayName : item.title; const summary = kind === 'profile' ? `${item.platform} · ${item.niche} · ${item.location} · ${item.audienceSize}` : `${item.type} · ${item.niche}`; details.append(text('h2', title || 'Untitled'), text('p', summary, 'admin-meta'), text('p', kind === 'profile' ? item.bio || '' : item.description || '', 'admin-meta'), text('p', `Owner: ${item.ownerEmail || 'Unknown'}`, 'admin-meta')); const review = document.createElement('div'); review.className = 'admin-review'; const decisionLabel = text('label', 'Decision'); const decision = document.createElement('select'); ['pending', 'approved', 'rejected', 'removed'].forEach(value => { const option = document.createElement('option'); option.value = value; option.textContent = value; option.selected = value === item.status; decision.append(option); }); decisionLabel.append(decision); const noteLabel = text('label', 'Private note'); const note = document.createElement('textarea'); note.value = item.adminNote || ''; note.placeholder = 'Reason or review note'; noteLabel.append(note); const save = text('button', 'Save decision'); save.addEventListener('click', async () => { save.disabled = true; save.textContent = 'Saving…'; try { await httpsCallable(functions, 'reviewCreatorSubmission')({ kind, id: item.id, decision: decision.value, note: note.value.trim() }); message.textContent = 'Decision saved.'; await load(); } catch (error) { console.error(error); message.textContent = error.message || 'Could not save the decision.'; save.disabled = false; save.textContent = 'Save decision'; } }); review.append(decisionLabel, noteLabel, save); card.append(details, review); return card; }
function render(data) { list.replaceChildren(); const profiles = data.profiles || [], opportunities = data.opportunities || []; if (!profiles.length && !opportunities.length) { const empty = document.createElement('div'); empty.className = 'admin-empty'; empty.append(text('b', 'No community submissions yet.'), text('span', 'New profiles and opportunities will appear here.')); list.append(empty); return; } if (profiles.length) { list.append(text('h2', 'Creator profiles')); profiles.forEach(item => list.append(card(item, 'profile'))); } if (opportunities.length) { list.append(text('h2', 'Collaboration opportunities')); opportunities.forEach(item => list.append(card(item, 'opportunity'))); } }
async function load() { try { const result = await httpsCallable(functions, 'getCreatorSubmissions')(); render(result.data); } catch (error) { console.error(error); list.innerHTML = '<div class="admin-empty"><b>This page is for the SMM Solutions admin account only.</b><span>Sign in using smmsolutionsbypabsrivera@gmail.com, then refresh.</span></div>'; } }
onAuthStateChanged(auth, user => { signIn.hidden = Boolean(user); if (user) load(); }); signIn.addEventListener('click', () => signInWithPopup(auth, provider).catch(error => message.textContent = error.message));
