const MARKETPLACE_ENDPOINT='';
const LISTING_FORM_URL='';
const grid=document.querySelector('#listing-grid'),search=document.querySelector('#listing-search'),category=document.querySelector('#listing-category');
let listings=[];
const money=value=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Number(value)||0);
function safeImage(url){try{const parsed=new URL(url);return parsed.protocol==='https:'||parsed.protocol==='http:'?parsed.href:''}catch{return''}}
function render(){const term=search.value.trim().toLowerCase(),selected=category.value;const visible=listings.filter(item=>{const text=[item.title,item.description,item.category,item.location].join(' ').toLowerCase();return(!term||text.includes(term))&&(selected==='all'||item.category===selected)});if(!visible.length){grid.innerHTML='<div class="listing-empty"><b>No approved listings found.</b><span>Try another search, or be the first to post one.</span></div>';return}grid.innerHTML='';visible.forEach(item=>{const card=document.createElement('article');card.className='listing-card';const image=safeImage(item.image);const imageMarkup=image?`<img src="${image}" alt="${item.title}" loading="lazy">`:'<span>No photo provided</span>';card.innerHTML=`<div class="listing-image">${imageMarkup}</div><div class="listing-body"><span class="listing-category"></span><h3></h3><div class="listing-price"></div><div class="listing-meta"></div><p class="listing-description"></p><a class="button button-primary" target="_blank" rel="noreferrer">Message seller <span>→</span></a></div>`;card.querySelector('.listing-category').textContent=item.category||'Other';card.querySelector('h3').textContent=item.title;card.querySelector('.listing-price').textContent=money(item.price);card.querySelector('.listing-meta').textContent=item.location||'Location not specified';card.querySelector('.listing-description').textContent=item.description||'';card.querySelector('a').href=item.contact;grid.append(card)})}
async function loadListings(){if(!MARKETPLACE_ENDPOINT){grid.innerHTML='<div class="listing-empty"><b>The marketplace is being prepared.</b><span>Please return soon or post your listing for review.</span></div>';return}try{const response=await fetch(MARKETPLACE_ENDPOINT);if(!response.ok)throw new Error('Could not load listings');listings=await response.json();render()}catch{grid.innerHTML='<div class="listing-empty"><b>Listings are temporarily unavailable.</b><span>Please refresh later or message SMM Solutions for help.</span></div>'}}
document.querySelectorAll('.listing-form-link').forEach(link=>{if(LISTING_FORM_URL)link.href=LISTING_FORM_URL;else link.addEventListener('click',event=>{event.preventDefault();alert('The posting form is being prepared. Please message SMM Solutions to submit a listing.')})});search.addEventListener('input',render);category.addEventListener('change',render);document.querySelector('#year').textContent=new Date().getFullYear();loadListings();
